# system configuration generated and used by the sysconfig module
build_time_vars = {'AC_APPLE_UNIVERSAL_BUILD': 0,
 'AIX_GENUINE_CPLUSPLUS': 0,
 'AR': 'ar',
 'ARFLAGS': 'rc',
 'ATHEOS_THREADS': 0,
 'BASECFLAGS': '-fno-strict-aliasing',
 'BASEMODLIBS': '',
 'BEOS_THREADS': 0,
 'BINDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/bin',
 'BINLIBDEST': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7',
 'BLDLIBRARY': 'libpython2.7.a',
 'BLDSHARED': 'gcc -bundle -undefined dynamic_lookup -L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib -Wl,-search_paths_first',
 'BUILDEXE': '.exe',
 'BUILDPYTHON': 'python.exe',
 'CC': 'gcc',
 'CCSHARED': '',
 'CFLAGS': '-fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes',
 'CFLAGSFORSHARED': '',
 'CONFIGFILES': 'configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in',
 'CONFIG_ARGS': "'--prefix' '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out' '--host=' '--disable-shared' '--with-system-ffi' '--enable-ipv6' '--enable-py-version-override=2.7.18+chromium.44' '--enable-unicode=ucs2' '--without-ensurepip' '--with-threads' '--enable-toolbox-glue' '--build=aarch64-apple-darwin' 'build_alias=aarch64-apple-darwin' 'host_alias=' 'LDFLAGS=-L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib -Wl,-search_paths_first' 'CPPFLAGS=-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/include'",
 'CONFINCLUDEDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include',
 'CONFINCLUDEPY': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include/python2.7',
 'COREPYTHONPATH': ':plat-darwin:plat-mac:plat-mac/lib-scriptpackages:lib-tk:lib-old',
 'COVERAGE_INFO': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/coverage.info',
 'COVERAGE_REPORT': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/lcov-report',
 'COVERAGE_REPORT_OPTIONS': '--no-branch-coverage --title "CPython lcov report"',
 'CPPFLAGS': '-I. -IInclude -I./Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/include',
 'CXX': 'g++',
 'C_THREADS': 0,
 'DESTDIRS': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7 /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7/lib-dynload',
 'DESTLIB': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7',
 'DESTPATH': '',
 'DESTSHARED': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7/lib-dynload',
 'DIRMODE': 755,
 'DIST': 'README ChangeLog configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in Include Lib Misc Demo Ext-dummy',
 'DISTDIRS': 'Include Lib Misc Demo Ext-dummy',
 'DISTFILES': 'README ChangeLog configure configure.ac acconfig.h pyconfig.h.in Makefile.pre.in',
 'DLINCLDIR': '.',
 'DLLLIBRARY': '',
 'DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754': 0,
 'DOUBLE_IS_BIG_ENDIAN_IEEE754': 0,
 'DOUBLE_IS_LITTLE_ENDIAN_IEEE754': 1,
 'DYNLOADFILE': 'dynload_shlib.o',
 'ENABLE_IPV6': 1,
 'ENSUREPIP': 'no',
 'EXE': '',
 'EXEMODE': 755,
 'EXTRAMACHDEPPATH': ':plat-mac:plat-mac/lib-scriptpackages',
 'EXTRAPLATDIR': 'plat-mac plat-mac/Carbon plat-mac/lib-scriptpackages \\',
 'EXTRATESTOPTS': '',
 'EXTRA_CFLAGS': '',
 'FILEMODE': 644,
 'FLOCK_NEEDS_LIBBSD': 0,
 'GETPGRP_HAVE_ARG': 0,
 'GETTIMEOFDAY_NO_TZ': 0,
 'GITBRANCH': '',
 'GITTAG': '',
 'GITVERSION': '',
 'GLHACK': '-Dclear=__GLclear',
 'GNULD': 'no',
 'HAVE_ACOSH': 1,
 'HAVE_ADDRINFO': 1,
 'HAVE_ALARM': 1,
 'HAVE_ALLOCA_H': 1,
 'HAVE_ALTZONE': 0,
 'HAVE_ASINH': 1,
 'HAVE_ASM_TYPES_H': 0,
 'HAVE_ATANH': 1,
 'HAVE_ATTRIBUTE_FORMAT_PARSETUPLE': 0,
 'HAVE_BIND_TEXTDOMAIN_CODESET': 0,
 'HAVE_BLUETOOTH_BLUETOOTH_H': 0,
 'HAVE_BLUETOOTH_H': 0,
 'HAVE_BROKEN_NICE': 0,
 'HAVE_BROKEN_PIPE_BUF': 0,
 'HAVE_BROKEN_POLL': 0,
 'HAVE_BROKEN_POSIX_SEMAPHORES': 0,
 'HAVE_BROKEN_PTHREAD_SIGMASK': 0,
 'HAVE_BROKEN_SEM_GETVALUE': 1,
 'HAVE_BROKEN_UNSETENV': 0,
 'HAVE_C99_BOOL': 1,
 'HAVE_CHFLAGS': 1,
 'HAVE_CHOWN': 1,
 'HAVE_CHROOT': 0,
 'HAVE_CLOCK': 1,
 'HAVE_COMPUTED_GOTOS': 1,
 'HAVE_CONFSTR': 1,
 'HAVE_CONIO_H': 0,
 'HAVE_COPYSIGN': 1,
 'HAVE_CRYPT_H': 0,
 'HAVE_CTERMID': 1,
 'HAVE_CTERMID_R': 1,
 'HAVE_CURSES_FILTER': 1,
 'HAVE_CURSES_H': 1,
 'HAVE_CURSES_HAS_KEY': 1,
 'HAVE_CURSES_IMMEDOK': 1,
 'HAVE_CURSES_IS_PAD': 0,
 'HAVE_CURSES_IS_TERM_RESIZED': 1,
 'HAVE_CURSES_RESIZETERM': 1,
 'HAVE_CURSES_RESIZE_TERM': 1,
 'HAVE_CURSES_SYNCOK': 1,
 'HAVE_CURSES_TYPEAHEAD': 1,
 'HAVE_CURSES_USE_ENV': 1,
 'HAVE_CURSES_WCHGAT': 1,
 'HAVE_DECL_ISFINITE': 1,
 'HAVE_DECL_ISINF': 1,
 'HAVE_DECL_ISNAN': 1,
 'HAVE_DECL_TZNAME': 0,
 'HAVE_DEVICE_MACROS': 1,
 'HAVE_DEV_PTC': 0,
 'HAVE_DEV_PTMX': 0,
 'HAVE_DIRECT_H': 0,
 'HAVE_DIRENT_H': 1,
 'HAVE_DLFCN_H': 1,
 'HAVE_DLOPEN': 1,
 'HAVE_DUP2': 1,
 'HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH': 1,
 'HAVE_DYNAMIC_LOADING': 1,
 'HAVE_EPOLL': 0,
 'HAVE_ERF': 1,
 'HAVE_ERFC': 1,
 'HAVE_ERRNO_H': 1,
 'HAVE_EXECV': 1,
 'HAVE_EXPM1': 1,
 'HAVE_FCHDIR': 1,
 'HAVE_FCHMOD': 1,
 'HAVE_FCHOWN': 1,
 'HAVE_FCNTL_H': 1,
 'HAVE_FDATASYNC': 0,
 'HAVE_FINITE': 0,
 'HAVE_FLOCK': 1,
 'HAVE_FORK': 1,
 'HAVE_FORKPTY': 1,
 'HAVE_FPATHCONF': 1,
 'HAVE_FSEEK64': 0,
 'HAVE_FSEEKO': 1,
 'HAVE_FSTATVFS': 1,
 'HAVE_FSYNC': 1,
 'HAVE_FTELL64': 0,
 'HAVE_FTELLO': 1,
 'HAVE_FTIME': 1,
 'HAVE_FTRUNCATE': 1,
 'HAVE_GAI_STRERROR': 1,
 'HAVE_GAMMA': 0,
 'HAVE_GCC_ASM_FOR_X87': 0,
 'HAVE_GETADDRINFO': 1,
 'HAVE_GETCWD': 1,
 'HAVE_GETC_UNLOCKED': 1,
 'HAVE_GETENTROPY': 0,
 'HAVE_GETGROUPS': 1,
 'HAVE_GETHOSTBYNAME': 1,
 'HAVE_GETHOSTBYNAME_R': 0,
 'HAVE_GETHOSTBYNAME_R_3_ARG': 0,
 'HAVE_GETHOSTBYNAME_R_5_ARG': 0,
 'HAVE_GETHOSTBYNAME_R_6_ARG': 0,
 'HAVE_GETITIMER': 1,
 'HAVE_GETLOADAVG': 1,
 'HAVE_GETLOGIN': 1,
 'HAVE_GETNAMEINFO': 1,
 'HAVE_GETPAGESIZE': 0,
 'HAVE_GETPEERNAME': 1,
 'HAVE_GETPGID': 1,
 'HAVE_GETPGRP': 1,
 'HAVE_GETPID': 1,
 'HAVE_GETPRIORITY': 1,
 'HAVE_GETPWENT': 1,
 'HAVE_GETRESGID': 0,
 'HAVE_GETRESUID': 0,
 'HAVE_GETSID': 1,
 'HAVE_GETSPENT': 0,
 'HAVE_GETSPNAM': 0,
 'HAVE_GETTIMEOFDAY': 1,
 'HAVE_GETWD': 1,
 'HAVE_GRP_H': 1,
 'HAVE_HSTRERROR': 1,
 'HAVE_HYPOT': 1,
 'HAVE_IEEEFP_H': 0,
 'HAVE_INET_ATON': 1,
 'HAVE_INET_PTON': 1,
 'HAVE_INITGROUPS': 1,
 'HAVE_INT32_T': 1,
 'HAVE_INT64_T': 1,
 'HAVE_INTTYPES_H': 1,
 'HAVE_IO_H': 0,
 'HAVE_KILL': 1,
 'HAVE_KILLPG': 1,
 'HAVE_KQUEUE': 1,
 'HAVE_LANGINFO_H': 1,
 'HAVE_LARGEFILE_SUPPORT': 0,
 'HAVE_LCHFLAGS': 1,
 'HAVE_LCHMOD': 1,
 'HAVE_LCHOWN': 1,
 'HAVE_LGAMMA': 1,
 'HAVE_LIBDL': 1,
 'HAVE_LIBDLD': 0,
 'HAVE_LIBIEEE': 0,
 'HAVE_LIBINTL_H': 0,
 'HAVE_LIBREADLINE': 1,
 'HAVE_LIBRESOLV': 0,
 'HAVE_LIBUTIL_H': 0,
 'HAVE_LINK': 1,
 'HAVE_LINUX_NETLINK_H': 0,
 'HAVE_LINUX_TIPC_H': 0,
 'HAVE_LOG1P': 1,
 'HAVE_LONG_DOUBLE': 1,
 'HAVE_LONG_LONG': 1,
 'HAVE_LSTAT': 1,
 'HAVE_MAKEDEV': 1,
 'HAVE_MEMMOVE': 1,
 'HAVE_MEMORY_H': 1,
 'HAVE_MKFIFO': 1,
 'HAVE_MKNOD': 1,
 'HAVE_MKTIME': 1,
 'HAVE_MMAP': 1,
 'HAVE_MREMAP': 0,
 'HAVE_NCURSES_H': 1,
 'HAVE_NDIR_H': 0,
 'HAVE_NETPACKET_PACKET_H': 0,
 'HAVE_NICE': 1,
 'HAVE_OPENPTY': 1,
 'HAVE_OSX105_SDK': 1,
 'HAVE_PATHCONF': 1,
 'HAVE_PAUSE': 1,
 'HAVE_PLOCK': 0,
 'HAVE_POLL': 1,
 'HAVE_POLL_H': 1,
 'HAVE_PROCESS_H': 0,
 'HAVE_PROTOTYPES': 1,
 'HAVE_PTH': 0,
 'HAVE_PTHREAD_ATFORK': 1,
 'HAVE_PTHREAD_DESTRUCTOR': 0,
 'HAVE_PTHREAD_H': 1,
 'HAVE_PTHREAD_INIT': 0,
 'HAVE_PTHREAD_SIGMASK': 1,
 'HAVE_PTY_H': 0,
 'HAVE_PUTENV': 1,
 'HAVE_READLINK': 1,
 'HAVE_REALPATH': 1,
 'HAVE_RL_CALLBACK': 1,
 'HAVE_RL_CATCH_SIGNAL': 1,
 'HAVE_RL_COMPLETION_APPEND_CHARACTER': 1,
 'HAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK': 1,
 'HAVE_RL_COMPLETION_MATCHES': 1,
 'HAVE_RL_COMPLETION_SUPPRESS_APPEND': 1,
 'HAVE_RL_PRE_INPUT_HOOK': 1,
 'HAVE_RL_RESIZE_TERMINAL': 1,
 'HAVE_ROUND': 1,
 'HAVE_SELECT': 1,
 'HAVE_SEM_GETVALUE': 1,
 'HAVE_SEM_OPEN': 1,
 'HAVE_SEM_TIMEDWAIT': 0,
 'HAVE_SEM_UNLINK': 1,
 'HAVE_SETEGID': 1,
 'HAVE_SETEUID': 1,
 'HAVE_SETGID': 1,
 'HAVE_SETGROUPS': 1,
 'HAVE_SETITIMER': 1,
 'HAVE_SETLOCALE': 1,
 'HAVE_SETPGID': 1,
 'HAVE_SETPGRP': 1,
 'HAVE_SETREGID': 1,
 'HAVE_SETRESGID': 0,
 'HAVE_SETRESUID': 0,
 'HAVE_SETREUID': 1,
 'HAVE_SETSID': 1,
 'HAVE_SETUID': 1,
 'HAVE_SETVBUF': 1,
 'HAVE_SHADOW_H': 0,
 'HAVE_SIGACTION': 1,
 'HAVE_SIGINTERRUPT': 1,
 'HAVE_SIGNAL_H': 1,
 'HAVE_SIGRELSE': 1,
 'HAVE_SNPRINTF': 1,
 'HAVE_SOCKADDR_SA_LEN': 1,
 'HAVE_SOCKADDR_STORAGE': 1,
 'HAVE_SOCKETPAIR': 1,
 'HAVE_SPAWN_H': 1,
 'HAVE_SSIZE_T': 1,
 'HAVE_STATVFS': 1,
 'HAVE_STAT_TV_NSEC': 0,
 'HAVE_STAT_TV_NSEC2': 1,
 'HAVE_STDARG_PROTOTYPES': 1,
 'HAVE_STDINT_H': 1,
 'HAVE_STDLIB_H': 1,
 'HAVE_STRDUP': 1,
 'HAVE_STRFTIME': 1,
 'HAVE_STRINGS_H': 1,
 'HAVE_STRING_H': 1,
 'HAVE_STROPTS_H': 0,
 'HAVE_STRUCT_STAT_ST_BIRTHTIME': 1,
 'HAVE_STRUCT_STAT_ST_BLKSIZE': 1,
 'HAVE_STRUCT_STAT_ST_BLOCKS': 1,
 'HAVE_STRUCT_STAT_ST_FLAGS': 1,
 'HAVE_STRUCT_STAT_ST_GEN': 1,
 'HAVE_STRUCT_STAT_ST_RDEV': 1,
 'HAVE_STRUCT_TM_TM_ZONE': 1,
 'HAVE_SYMLINK': 1,
 'HAVE_SYSCONF': 1,
 'HAVE_SYSEXITS_H': 1,
 'HAVE_SYS_AUDIOIO_H': 0,
 'HAVE_SYS_BSDTTY_H': 0,
 'HAVE_SYS_DIR_H': 0,
 'HAVE_SYS_EPOLL_H': 0,
 'HAVE_SYS_EVENT_H': 1,
 'HAVE_SYS_FILE_H': 1,
 'HAVE_SYS_LOADAVG_H': 0,
 'HAVE_SYS_LOCK_H': 1,
 'HAVE_SYS_MKDEV_H': 0,
 'HAVE_SYS_MODEM_H': 0,
 'HAVE_SYS_NDIR_H': 0,
 'HAVE_SYS_PARAM_H': 1,
 'HAVE_SYS_POLL_H': 1,
 'HAVE_SYS_RANDOM_H': 1,
 'HAVE_SYS_RESOURCE_H': 1,
 'HAVE_SYS_SELECT_H': 1,
 'HAVE_SYS_SOCKET_H': 1,
 'HAVE_SYS_STATVFS_H': 1,
 'HAVE_SYS_STAT_H': 1,
 'HAVE_SYS_SYSMACROS_H': 0,
 'HAVE_SYS_TERMIO_H': 0,
 'HAVE_SYS_TIMES_H': 1,
 'HAVE_SYS_TIME_H': 1,
 'HAVE_SYS_TYPES_H': 1,
 'HAVE_SYS_UN_H': 1,
 'HAVE_SYS_UTSNAME_H': 1,
 'HAVE_SYS_WAIT_H': 1,
 'HAVE_TCGETPGRP': 1,
 'HAVE_TCSETPGRP': 1,
 'HAVE_TEMPNAM': 1,
 'HAVE_TERMIOS_H': 1,
 'HAVE_TERM_H': 1,
 'HAVE_TGAMMA': 1,
 'HAVE_THREAD_H': 0,
 'HAVE_TIMEGM': 1,
 'HAVE_TIMES': 1,
 'HAVE_TMPFILE': 1,
 'HAVE_TMPNAM': 1,
 'HAVE_TMPNAM_R': 0,
 'HAVE_TM_ZONE': 1,
 'HAVE_TRUNCATE': 1,
 'HAVE_TZNAME': 0,
 'HAVE_UCS4_TCL': 0,
 'HAVE_UINT32_T': 1,
 'HAVE_UINT64_T': 1,
 'HAVE_UINTPTR_T': 1,
 'HAVE_UNAME': 1,
 'HAVE_UNISTD_H': 1,
 'HAVE_UNSETENV': 1,
 'HAVE_USABLE_WCHAR_T': 0,
 'HAVE_UTIL_H': 1,
 'HAVE_UTIMES': 1,
 'HAVE_UTIME_H': 1,
 'HAVE_WAIT3': 1,
 'HAVE_WAIT4': 1,
 'HAVE_WAITPID': 1,
 'HAVE_WCHAR_H': 1,
 'HAVE_WCSCOLL': 1,
 'HAVE_WORKING_TZSET': 1,
 'HAVE_ZLIB_COPY': 1,
 'HAVE__GETPTY': 0,
 'HOST_GNU_TYPE': 'aarch64-apple-darwin',
 'HURD_C_THREADS': 0,
 'INCLDIRSTOMAKE': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include/python2.7 /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include/python2.7',
 'INCLUDEDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include',
 'INCLUDEPY': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/include/python2.7',
 'INSTALL': '/usr/bin/install -c',
 'INSTALL_DATA': '/usr/bin/install -c -m 644',
 'INSTALL_PROGRAM': '/usr/bin/install -c',
 'INSTALL_SCRIPT': '/usr/bin/install -c',
 'INSTALL_SHARED': '/usr/bin/install -c -m 555',
 'INSTSONAME': 'libpython2.7.a',
 'LDCXXSHARED': 'g++ -bundle -undefined dynamic_lookup',
 'LDFLAGS': '-L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib -Wl,-search_paths_first',
 'LDLAST': '-lpthread',
 'LDLIBRARY': 'libpython2.7.a',
 'LDLIBRARYDIR': '',
 'LDSHARED': 'gcc -bundle -undefined dynamic_lookup -L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib -Wl,-search_paths_first',
 'LIBC': '',
 'LIBDEST': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7',
 'LIBDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib',
 'LIBFFI_INCLUDEDIR': '',
 'LIBM': '',
 'LIBOBJDIR': 'Python/',
 'LIBOBJS': '',
 'LIBP': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7',
 'LIBPC': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/pkgconfig',
 'LIBPL': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7/config',
 'LIBRARY': 'libpython2.7.a',
 'LIBRARY_OBJS': '\\',
 'LIBS': '-ldl  -framework CoreFoundation',
 'LIBSUBDIRS': 'lib-tk lib-tk/test lib-tk/test/test_tkinter \\',
 'LINKCC': 'gcc',
 'LINKFORSHARED': '-u _PyMac_Error',
 'LLVM_PROF_ERR': 'no',
 'LLVM_PROF_FILE': 'LLVM_PROFILE_FILE="code-%p.profclangr"',
 'LLVM_PROF_MERGER': '/usr/bin/xcrun llvm-profdata merge -output=code.profclangd *.profclangr',
 'LN': 'ln',
 'LOCALMODLIBS': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libbz2.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libreadline.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libpanel.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libncurses.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libsqlite3.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libz.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libssl.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libcrypto.a  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_io -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -L/usr/lib/termcap -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -L/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib \'-DMODULE_NAME="sqlite3"\' \'-DSQLITE_OMIT_LOAD_EXTENSION=1\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_sqlite -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wl,-search_paths_first  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  \'-DHAVE_NDBM_H=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wl,-search_paths_first  \'-DHAVE_EXPAT_CONFIG_H=1\' \'-DXML_POOR_ENTROPY=1\' \'-DUSE_PYEXPAT_CAPI=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  \'-DHAVE_EXPAT_CONFIG_H=1\' \'-DXML_POOR_ENTROPY=1\' \'-DUSE_PYEXPAT_CAPI=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_multiprocessing -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -framework SystemConfiguration -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework ApplicationServices  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework ApplicationServices  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/_ctypes/darwin -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -DUSING_MALLOC_CLOSURE_DOT_C=1 -DMACOSX -DUSING_APPLE_OS_LIBFFI=1 -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1 -lffi           -L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib -lz',
 'MACHDEP': 'darwin',
 'MACHDEPPATH': ':plat-darwin',
 'MACHDEPS': 'plat-darwin plat-mac plat-mac/Carbon plat-mac/lib-scriptpackages \\',
 'MACHDEP_OBJS': 'Python/mactoolboxglue.o',
 'MACHDESTLIB': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib/python2.7',
 'MACH_C_THREADS': 0,
 'MACOSX_DEPLOYMENT_TARGET': '11.0',
 'MAINCC': 'gcc',
 'MAJOR_IN_MKDEV': 0,
 'MAJOR_IN_SYSMACROS': 0,
 'MAKESETUP': './Modules/makesetup',
 'MANDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/share/man',
 'MEMTESTOPTS': '-l -x test_subprocess test_io test_lib2to3 \\ -x test_dl test___all__ test_fork1 \\',
 'MKDIR_P': './install-sh -c -d',
 'MODLIBS': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libbz2.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libreadline.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libpanel.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libncurses.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libsqlite3.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libz.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libssl.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libcrypto.a  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_io -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -L/usr/lib/termcap -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -L/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib \'-DMODULE_NAME="sqlite3"\' \'-DSQLITE_OMIT_LOAD_EXTENSION=1\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_sqlite -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wl,-search_paths_first  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  \'-DHAVE_NDBM_H=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wl,-search_paths_first  \'-DHAVE_EXPAT_CONFIG_H=1\' \'-DXML_POOR_ENTROPY=1\' \'-DUSE_PYEXPAT_CAPI=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  \'-DHAVE_EXPAT_CONFIG_H=1\' \'-DXML_POOR_ENTROPY=1\' \'-DUSE_PYEXPAT_CAPI=None\' -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_multiprocessing -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -framework SystemConfiguration -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework CoreFoundation  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework Carbon  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework ApplicationServices  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -Wno-deprecated-declarations -framework ApplicationServices  -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/_ctypes/darwin -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -DUSING_MALLOC_CLOSURE_DOT_C=1 -DMACOSX -DUSING_APPLE_OS_LIBFFI=1 -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1 -lffi           -L/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib -lz',
 'MODOBJS': 'Modules/threadmodule.o  Modules/signalmodule.o  Modules/_struct.o  Modules/_ctypes_test.o  Modules/arraymodule.o  Modules/cmathmodule.o Modules/_math.o  Modules/mathmodule.o Modules/_math.o  Modules/stropmodule.o  Modules/timemodule.o  Modules/datetimemodule.o Modules/timemodule.o  Modules/itertoolsmodule.o  Modules/future_builtins.o  Modules/_randommodule.o  Modules/_collectionsmodule.o  Modules/_bisectmodule.o  Modules/_heapqmodule.o  Modules/operator.o  Modules/bufferedio.o Modules/bytesio.o Modules/fileio.o Modules/iobase.o Modules/_iomodule.o Modules/stringio.o Modules/textio.o  Modules/_functoolsmodule.o  Modules/_json.o  Modules/_hotshot.o  Modules/_lsprof.o Modules/rotatingtree.o  Modules/unicodedata.o  Modules/_localemodule.o  Modules/fcntlmodule.o  Modules/grpmodule.o  Modules/selectmodule.o  Modules/parsermodule.o  Modules/cStringIO.o  Modules/cPickle.o  Modules/mmapmodule.o  Modules/syslogmodule.o  Modules/audioop.o  Modules/readline.o  Modules/cryptmodule.o  Modules/_csv.o  Modules/socketmodule.o Modules/timemodule.o  Modules/_ssl.o  Modules/_hashopenssl.o  Modules/cache.o Modules/connection.o Modules/cursor.o Modules/microprotocols.o Modules/module.o Modules/prepare_protocol.o Modules/row.o Modules/statement.o Modules/util.o  Modules/bsddbmodule.o  Modules/dbmmodule.o  Modules/termios.o  Modules/resource.o  Modules/nismodule.o  Modules/_cursesmodule.o  Modules/_curses_panel.o  Modules/bz2module.o  Modules/pyexpat.o Modules/xmlparse.o Modules/xmlrole.o Modules/xmltok.o  Modules/_elementtree.o  Modules/multibytecodec.o  Modules/_codecs_kr.o  Modules/_codecs_jp.o  Modules/_codecs_cn.o  Modules/_codecs_tw.o  Modules/_codecs_hk.o  Modules/_codecs_iso2022.o  Modules/multiprocessing.o Modules/socket_connection.o Modules/semaphore.o  Modules/_scproxy.o  Modules/_CFmodule.o Modules/pycfbridge.o  Modules/autoGIL.o  Modules/ColorPickermodule.o  Modules/gestaltmodule.o  Modules/MacOS.o  Modules/Nav.o  Modules/OSATerminology.o  Modules/icgluemodule.o  Modules/_AEmodule.o  Modules/_AHmodule.o  Modules/_Appmodule.o  Modules/_CarbonEvtmodule.o  Modules/_Cmmodule.o  Modules/_Ctlmodule.o  Modules/_Dlgmodule.o  Modules/_Dragmodule.o  Modules/_Evtmodule.o  Modules/_Filemodule.o  Modules/_Foldermodule.o  Modules/_Fmmodule.o  Modules/_Helpmodule.o  Modules/_Icnmodule.o  Modules/_IBCarbon.o  Modules/_Listmodule.o  Modules/_Menumodule.o  Modules/_Mltemodule.o  Modules/_OSAmodule.o  Modules/_Resmodule.o  Modules/_Qdmodule.o  Modules/_Qdoffsmodule.o  Modules/_Scrapmodule.o  Modules/_Sndmodule.o  Modules/_TEmodule.o  Modules/_Winmodule.o  Modules/_Launchmodule.o  Modules/_CGmodule.o  Modules/_ctypes.o Modules/callbacks.o Modules/callproc.o Modules/stgdict.o Modules/cfield.o Modules/malloc_closure.o  Modules/posixmodule.o  Modules/errnomodule.o  Modules/pwdmodule.o  Modules/_sre.o  Modules/_codecsmodule.o  Modules/_weakref.o  Modules/zipimport.o  Modules/symtablemodule.o  Modules/binascii.o  Modules/zlibmodule.o  Modules/xxsubtype.o',
 'MODULE_OBJS': '\\',
 'MOD_ATTACHMENTS___ctypes': '-lffi',
 'MOD_COMMON_ATTACH': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libbz2.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libreadline.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libpanel.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libncurses.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libsqlite3.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libz.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libssl.a /opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/lib/libcrypto.a',
 'MOD_DEFINES___elementtree': "'-DHAVE_EXPAT_CONFIG_H=1' '-DXML_POOR_ENTROPY=1' '-DUSE_PYEXPAT_CAPI=None'",
 'MOD_DEFINES___sqlite3': '\'-DMODULE_NAME="sqlite3"\' \'-DSQLITE_OMIT_LOAD_EXTENSION=1\'',
 'MOD_DEFINES__dbm': "'-DHAVE_NDBM_H=None'",
 'MOD_DEFINES__pyexpat': "'-DHAVE_EXPAT_CONFIG_H=1' '-DXML_POOR_ENTROPY=1' '-DUSE_PYEXPAT_CAPI=None'",
 'MOD_EXTRA_COMPILE__ColorPicker': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE__MacOS': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE__Nav': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE__OSATerminology': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___AE': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___AH': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___App': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___CF': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___CG': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___CarbonEvt': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Cm': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Ctl': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Dlg': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Drag': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Evt': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___File': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Fm': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Folder': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Help': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___IBCarbon': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Icn': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Launch': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___List': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Menu': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Mlte': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___OSA': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Qd': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Qdoffs': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Res': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Scrap': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Snd': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___TE': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___Win': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE___ctypes': '-DUSING_MALLOC_CLOSURE_DOT_C=1 -DMACOSX -DUSING_APPLE_OS_LIBFFI=1 -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1',
 'MOD_EXTRA_COMPILE__autoGIL': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE__gestalt': '-Wno-deprecated-declarations',
 'MOD_EXTRA_COMPILE__icglue': '-Wno-deprecated-declarations',
 'MOD_EXTRA_LINK__ColorPicker': '-framework Carbon',
 'MOD_EXTRA_LINK__MacOS': '-framework Carbon',
 'MOD_EXTRA_LINK__Nav': '-framework Carbon',
 'MOD_EXTRA_LINK__OSATerminology': '-framework Carbon',
 'MOD_EXTRA_LINK___AE': '-framework Carbon',
 'MOD_EXTRA_LINK___AH': '-framework Carbon',
 'MOD_EXTRA_LINK___App': '-framework Carbon',
 'MOD_EXTRA_LINK___CF': '-framework CoreFoundation',
 'MOD_EXTRA_LINK___CG': '-framework ApplicationServices',
 'MOD_EXTRA_LINK___CarbonEvt': '-framework Carbon',
 'MOD_EXTRA_LINK___Cm': '-framework Carbon',
 'MOD_EXTRA_LINK___Ctl': '-framework Carbon',
 'MOD_EXTRA_LINK___Dlg': '-framework Carbon',
 'MOD_EXTRA_LINK___Drag': '-framework Carbon',
 'MOD_EXTRA_LINK___Evt': '-framework Carbon',
 'MOD_EXTRA_LINK___File': '-framework Carbon',
 'MOD_EXTRA_LINK___Fm': '-framework Carbon',
 'MOD_EXTRA_LINK___Folder': '-framework Carbon',
 'MOD_EXTRA_LINK___Help': '-framework Carbon',
 'MOD_EXTRA_LINK___IBCarbon': '-framework Carbon',
 'MOD_EXTRA_LINK___Icn': '-framework Carbon',
 'MOD_EXTRA_LINK___Launch': '-framework ApplicationServices',
 'MOD_EXTRA_LINK___List': '-framework Carbon',
 'MOD_EXTRA_LINK___Menu': '-framework Carbon',
 'MOD_EXTRA_LINK___Mlte': '-framework Carbon',
 'MOD_EXTRA_LINK___OSA': '-framework Carbon',
 'MOD_EXTRA_LINK___Qd': '-framework Carbon',
 'MOD_EXTRA_LINK___Qdoffs': '-framework Carbon',
 'MOD_EXTRA_LINK___Res': '-framework Carbon',
 'MOD_EXTRA_LINK___Scrap': '-framework Carbon',
 'MOD_EXTRA_LINK___Snd': '-framework Carbon',
 'MOD_EXTRA_LINK___TE': '-framework Carbon',
 'MOD_EXTRA_LINK___Win': '-framework Carbon',
 'MOD_EXTRA_LINK___locale': '-framework CoreFoundation',
 'MOD_EXTRA_LINK___scproxy': '-framework SystemConfiguration -framework CoreFoundation',
 'MOD_EXTRA_LINK___sqlite3': '-Wl,-search_paths_first',
 'MOD_EXTRA_LINK__autoGIL': '-framework CoreFoundation',
 'MOD_EXTRA_LINK__bz2': '-Wl,-search_paths_first',
 'MOD_EXTRA_LINK__gestalt': '-framework Carbon',
 'MOD_EXTRA_LINK__icglue': '-framework Carbon',
 'MOD_INCLUDES__ColorPicker': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__MacOS': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__Nav': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__OSATerminology': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___AE': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___AH': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___App': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___CF': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___CG': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___CarbonEvt': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Cm': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Ctl': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Dlg': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Drag': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Evt': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___File': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Fm': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Folder': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Help': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___IBCarbon': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Icn': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Launch': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___List': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Menu': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Mlte': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___OSA': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Qd': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Qdoffs': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Res': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Scrap': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Snd': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___TE': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___Win': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___bisect': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_cn': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_hk': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_iso2022': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_jp': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_kr': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___codecs_tw': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___collections': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___csv': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___ctypes': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/_ctypes/darwin -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___ctypes_test': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___curses': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___curses_panel': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___elementtree': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___functools': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___hashlib': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___heapq': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___hotshot': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___io': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_io -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___json': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___locale': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___lsprof': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___multibytecodec': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___multiprocessing': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_multiprocessing -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___random': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___scproxy': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___socket': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___sqlite3': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Modules/Modules/_sqlite -I/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___ssl': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES___struct': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__array': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__audioop': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__autoGIL': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__bsddb185': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__bz2': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__cPickle': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__cStringIO': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__cmath': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__crypt': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__datetime': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__dbm': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__fcntl': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__future_builtins': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__gestalt': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__grp': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__icglue': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__itertools': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__math': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__mmap': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__nis': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__operator': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__parser': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__pyexpat': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/./Modules/expat -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__readline': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__resource': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__select': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__strop': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__syslog': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__termios': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__time': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MOD_INCLUDES__unicodedata': '-I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout/Mac/Include',
 'MULTIARCH': '',
 'MVWDELCH_IS_EXPRESSION': 1,
 'OBJECT_OBJS': '\\',
 'OLDPATH': ':lib-old',
 'OPT': '-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes',
 'OTHER_LIBTOOL_OPT': '',
 'PACKAGE_BUGREPORT': 0,
 'PACKAGE_NAME': 0,
 'PACKAGE_STRING': 0,
 'PACKAGE_TARNAME': 0,
 'PACKAGE_URL': 0,
 'PACKAGE_VERSION': 0,
 'PARSER_HEADERS': '\\',
 'PARSER_OBJS': '\\ Parser/myreadline.o Parser/tokenizer.o',
 'PGEN': 'Parser/pgen',
 'PGENOBJS': '\\ \\',
 'PGENSRCS': '\\ \\',
 'PGOBJS': '\\',
 'PGO_PROF_GEN_FLAG': '-fprofile-instr-generate',
 'PGO_PROF_USE_FLAG': '-fprofile-instr-use=code.profclangd',
 'PGSRCS': '\\',
 'PLATDIR': 'plat-darwin',
 'PLATMACDIRS': 'plat-mac plat-mac/Carbon plat-mac/lib-scriptpackages \\',
 'PLATMACPATH': ':plat-mac:plat-mac/lib-scriptpackages',
 'POBJS': '\\',
 'POSIX_SEMAPHORES_NOT_ENABLED': 0,
 'PROFILE_TASK': '-m test.regrtest --pgo -x test_asyncore test_gdb test_multiprocessing test_subprocess',
 'PSRCS': '\\',
 'PTHREAD_SYSTEM_SCHED_SUPPORTED': 0,
 'PURIFY': '',
 'PYLONG_BITS_IN_DIGIT': 0,
 'PYTHON': 'python',
 'PYTHONFRAMEWORK': '',
 'PYTHONFRAMEWORKDIR': 'no-framework',
 'PYTHONFRAMEWORKINSTALLDIR': '',
 'PYTHONFRAMEWORKPREFIX': '',
 'PYTHONPATH': ':plat-darwin:plat-mac:plat-mac/lib-scriptpackages:lib-tk:lib-old',
 'PYTHON_FOR_BUILD': './python.exe -E',
 'PYTHON_FOR_REGEN': 'python2.7',
 'PYTHON_HEADERS': '\\',
 'PYTHON_OBJS': '\\',
 'PY_CFLAGS': '-fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/deps_prefix/include  -DPy_BUILD_CORE',
 'PY_FORMAT_LONG_LONG': '"ll"',
 'PY_FORMAT_SIZE_T': '"z"',
 'PY_UNICODE_TYPE': 'unsigned short',
 'PY_VERSION_OVERRIDE': '"2.7.18+chromium.44"',
 'Py_DEBUG': 0,
 'Py_ENABLE_SHARED': 0,
 'Py_UNICODE_SIZE': 2,
 'Py_USING_UNICODE': 1,
 'QUICKTESTOPTS': '-l -x test_subprocess test_io test_lib2to3 \\',
 'RANLIB': 'ranlib',
 'RESSRCDIR': 'Mac/Resources/framework',
 'RETSIGTYPE': 'void',
 'RUNSHARED': '',
 'SCRIPTDIR': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/lib',
 'SETPGRP_HAVE_ARG': 0,
 'SGI_ABI': '',
 'SHELL': '/bin/sh',
 'SHLIBS': '-ldl  -framework CoreFoundation',
 'SHLIB_EXT': '".so"',
 'SIGNAL_OBJS': '',
 'SIGNED_RIGHT_SHIFT_ZERO_FILLS': 1,
 'SITEPATH': '',
 'SIZEOF_DOUBLE': 8,
 'SIZEOF_FLOAT': 4,
 'SIZEOF_FPOS_T': 8,
 'SIZEOF_INT': 4,
 'SIZEOF_LONG': 8,
 'SIZEOF_LONG_DOUBLE': 8,
 'SIZEOF_LONG_LONG': 8,
 'SIZEOF_OFF_T': 8,
 'SIZEOF_PID_T': 4,
 'SIZEOF_PTHREAD_T': 8,
 'SIZEOF_SHORT': 2,
 'SIZEOF_SIZE_T': 8,
 'SIZEOF_TIME_T': 8,
 'SIZEOF_UINTPTR_T': 8,
 'SIZEOF_VOID_P': 8,
 'SIZEOF_WCHAR_T': 4,
 'SIZEOF__BOOL': 1,
 'SO': '.so',
 'SRCDIRS': 'Parser Objects Python Modules Modules/_io',
 'SRC_GDB_HOOKS': './Tools/gdb/libpython.py',
 'STDC_HEADERS': 1,
 'STRICT_SYSV_CURSES': "/* Don't use ncurses extensions */",
 'STRINGLIB_HEADERS': '\\',
 'SUBDIRS': '',
 'SUBDIRSTOO': 'Include Lib Misc Demo',
 'SYSLIBS': '',
 'SYS_SELECT_WITH_SYS_TIME': 1,
 'TANH_PRESERVES_ZERO_SIGN': 1,
 'TCLTK_INCLUDES': '',
 'TCLTK_LIBS': '',
 'TESTOPTS': '-l',
 'TESTPATH': '',
 'TESTPROG': './Lib/test/regrtest.py',
 'TESTPYTHON': './python.exe -Wd -3 -E -tt',
 'TESTPYTHONOPTS': '',
 'THREADOBJ': 'Python/thread.o',
 'TIME_WITH_SYS_TIME': 1,
 'TKPATH': ':lib-tk',
 'TM_IN_SYS_TIME': 0,
 'UNICODE_OBJS': 'Objects/unicodeobject.o Objects/unicodectype.o',
 'UNIVERSALSDK': '',
 'USE_COMPUTED_GOTOS': 0,
 'USE_TOOLBOX_OBJECT_GLUE': 1,
 'VA_LIST_IS_ARRAY': 0,
 'VERSION': '2.7',
 'WANT_SIGFPE_HANDLER': 0,
 'WANT_WCTYPE_FUNCTIONS': 0,
 'WINDOW_HAS_FLAGS': 1,
 'WITH_DOC_STRINGS': 1,
 'WITH_DYLD': 1,
 'WITH_LIBINTL': 0,
 'WITH_NEXT_FRAMEWORK': 0,
 'WITH_PYMALLOC': 1,
 'WITH_THREAD': 1,
 'WITH_TSC': 0,
 'WITH_VALGRIND': 0,
 'X87_DOUBLE_ROUNDING': 0,
 'XMLLIBSUBDIRS': 'xml xml/dom xml/etree xml/parsers xml/sax',
 'abs_builddir': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout',
 'abs_srcdir': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout',
 'build': 'aarch64-apple-darwin',
 'datarootdir': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out/share',
 'exec_prefix': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out',
 'host': 'aarch64-apple-darwin',
 'prefix': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/out',
 'srcdir': '.',
 'srcroot': '/opt/s/w/ir/x/w/3pp/wd/tools/cpython/mac-arm64/2.7.18/checkout'}
