#!/bin/sh
if test "z$*" = zversion ||
   test "z$*" = z--version
then
	echo 'git-gui version 0.21.GITGUI'
else
	libdir="${GIT_GUI_LIB_DIR:-/opt/s/w/ir/x/w/3pp/wd/tools/git/mac-arm64/2.39.1/out/share/git-gui/lib}"
	exec "$libdir/Git Gui.app/Contents/MacOS/Wish" "$0" "$@"
fi
